# 20171018 - My lab 01 notes - NumPy

## Basic data structures

In [1]:
import numpy as np

array1D = np.array([1,2,3,4,5,6,7,8])
array2D = np.array([[1,2,3,4],[5,6,7,8]])

#Standard print
print('Data in arr1D:\n', array1D)
print('Data in arr2D:\n', array2D)

#The last line is evaluated
array1D
array2D

Data in arr1D:
 [1 2 3 4 5 6 7 8]
Data in arr2D:
 [[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Creating arrays

In [39]:
print(type(arr))
print(arr.shape)

array2D = np.zeros((2,4))
print(array2D)

array2D = np.ones((2,4))
print(array2D)

array2D = np.full((2,4),0.8)
print(array2D)

array2D = np.random.random((2,4))
print(array2D)

<class 'numpy.ndarray'>
(8,)
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.8  0.8  0.8  0.8]
 [ 0.8  0.8  0.8  0.8]]
[[ 0.62390991  0.6250513   0.45583278  0.26058447]
 [ 0.80674552  0.27583374  0.91661995  0.33935497]]


## Statistics

In [3]:
print('\n Standard deviation of array')
print(np.std(arr))

print('\n Numpy 2-dim array')
tab10n5 = np.random.randn(10,5)

print(tab10n5)
print('\n Standard deviation of array')
print(np.std(tab10n5))


 Standard deviation of array
1.41421356237

 Numpy 2-dim array
[[ 0.70877841  1.08488473  0.75614345  0.39343475 -1.09159538]
 [ 0.73399812  0.39836127 -0.75161155  0.27135876 -1.45327927]
 [ 0.8422371   0.27850071 -0.67032354  0.83166768 -0.66553294]
 [ 1.72591683 -0.66077105 -0.33339501  1.21957037 -0.67715499]
 [ 0.62372137 -1.09054098  1.28462688  0.24163735  0.04444997]
 [-1.71017295 -0.14348626 -0.51398444 -0.4380322  -0.63838363]
 [-2.05250016 -1.5312893  -1.13695393 -2.23734054  1.1419015 ]
 [ 1.18848575  1.94468234 -0.55002099  0.02451287 -0.90908412]
 [ 0.17940305 -0.67521462 -0.76642602  0.82111902 -1.08632999]
 [-0.62226332 -0.44511244 -1.49345312  0.92641361 -0.97935561]]

 Standard deviation of array
0.988539226533
